"""Week7 单 Agent 基线实现。"""
import logging
from typing import Any, Dict, List, Optional

from agent.nodes.intent_parse import detect_query_type, extract_entities
from agent.nodes.result_interpret import build_result_details, format_results_summary
from agent.nodes.sql_generate import build_schema_description, extract_sql_from_llm_response, generate_sql_with_rules
from agent.state import get_field_mapping
from config import DEEPSEEK_API_KEY
from services.conversation_service import extract_limit, extract_time_range
from services.db_service import get_db_service
from services.llm_service import get_llm_service


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def build_full_schema_context(db_service: Any) -> List[Dict[str, Any]]:
    """加载全量 schema，供单 Agent 直接生成 SQL。"""
    schemas: List[Dict[str, Any]] = []
    for table_name in db_service.get_table_names():
        table_info = db_service.get_table_info(table_name)
        schemas.append({
            "table_name": table_name,
            "ddl": db_service.get_table_schema(table_name),
            "columns": table_info["columns"],
            "row_count": table_info["row_count"],
            "primary_keys": table_info["primary_keys"],
            "foreign_keys": table_info["foreign_keys"],
        })
    return schemas


def build_baseline_intent(question: str) -> Dict[str, Any]:
    """单 Agent 基线只基于当前问题做轻量解析。"""
    intent = {
        "query_type": detect_query_type(question),
        "entities": extract_entities(question),
        "time_range": extract_time_range(question),
        "limit": extract_limit(question) or 100,
        "is_follow_up": False,
        "reference_question": "",
    }
    if intent["time_range"]:
        intent["time_expression"] = get_field_mapping(intent["time_range"])
    return intent


def run_single_agent_baseline(question: str, chat_history: Optional[List[Dict[str, Any]]] = None) -> Dict[str, Any]:
    """执行单 Agent 基线流程：直接生成 SQL、校验并执行。"""
    db_service = get_db_service()
    schemas = build_full_schema_context(db_service)
    intent = build_baseline_intent(question)
    schema_text = build_schema_description(schemas)

    generated_sql = ""
    try:
        if not DEEPSEEK_API_KEY:
            raise ValueError("DEEPSEEK_API_KEY 未设置")

        llm = get_llm_service()
        response = llm.generate_sql(
            schemas=schema_text,
            question=question,
            intent=intent,
            examples="",
            retry_hint="",
        )
        generated_sql = extract_sql_from_llm_response(response)
        logger.info("[Baseline] SQL generated by LLM")
    except Exception as exc:
        logger.warning(f"[Baseline] LLM unavailable, fallback to rules: {exc}")
        generated_sql = generate_sql_with_rules(question, intent, schemas)

    generated_sql = (generated_sql or "").strip()
    normalized_sql = generated_sql.lower()
    if not generated_sql or not (normalized_sql.startswith("select") or normalized_sql.startswith("with")):
        generated_sql = generate_sql_with_rules(question, intent, schemas)


    validation_result: Dict[str, Any]
    query_result: List[Dict[str, Any]] = []
    execution_stats: Dict[str, Any] = {
        "validation_attempted": True,
        "fix_attempted": False,
        "fix_success": False,
        "fix_strategy": "",
        "safety_blocked": False,
        "execution_attempted": False,
        "execution_success": False,
        "execution_error": "",
    }

    is_safe, safety_error = db_service.is_safe_sql(generated_sql)
    if not is_safe:
        execution_stats.update({
            "validation_passed": False,
            "validation_type": "security",
            "safety_blocked": True,
            "execution_error": safety_error or "",
        })
        validation_result = {
            "valid": False,
            "error": safety_error,
            "corrected_sql": None,
            "validation_type": "security",
        }
        return build_baseline_state(question, chat_history, intent, schemas, generated_sql, validation_result, query_result, execution_stats)

    explain_result = db_service.explain_query(generated_sql)
    if not explain_result.get("valid"):
        error_message = str(explain_result.get("error") or "SQL validation failed")
        execution_stats.update({
            "validation_passed": False,
            "validation_type": "explain",
            "execution_error": error_message,
        })
        validation_result = {
            "valid": False,
            "error": error_message,
            "corrected_sql": None,
            "validation_type": "explain",
        }
        return build_baseline_state(question, chat_history, intent, schemas, generated_sql, validation_result, query_result, execution_stats)

    validation_result = {
        "valid": True,
        "error": None,
        "corrected_sql": generated_sql,
        "validation_type": "explain",
        "explain": explain_result.get("explain", [])[:3],
    }
    execution_stats.update({
        "validation_passed": True,
        "validation_type": "explain",
    })

    try:
        query_result = db_service.execute_query(generated_sql)
        execution_stats.update({
            "execution_attempted": True,
            "execution_success": True,
            "execution_error": "",
        })
    except Exception as exc:
        error_message = str(exc)
        validation_result = {
            "valid": False,
            "error": error_message,
            "corrected_sql": generated_sql,
            "validation_type": "execution",
        }
        execution_stats.update({
            "execution_attempted": True,
            "execution_success": False,
            "execution_error": error_message,
        })

    return build_baseline_state(question, chat_history, intent, schemas, generated_sql, validation_result, query_result, execution_stats)


def build_baseline_state(
    question: str,
    chat_history: Optional[List[Dict[str, Any]]],
    intent: Dict[str, Any],
    schemas: List[Dict[str, Any]],
    generated_sql: str,
    validation_result: Dict[str, Any],
    query_result: List[Dict[str, Any]],
    execution_stats: Dict[str, Any],
) -> Dict[str, Any]:
    """构造与流水线兼容的返回状态。"""
    if validation_result.get("valid") and query_result:
        final_answer = f"{format_results_summary(query_result)}\n\n{build_result_details(query_result, generated_sql, len(query_result))}"
    elif validation_result.get("valid"):
        final_answer = "查询执行成功，但没有找到匹配的数据。"
    else:
        final_answer = f"查询失败：{validation_result.get('error', '未知错误')}"

    return {
        "question": question,
        "resolved_question": question,
        "is_follow_up": False,
        "messages": [],
        "chat_history": chat_history or [],
        "intent": intent,
        "relevant_schemas": schemas,
        "generated_sql": generated_sql,
        "validation_result": validation_result,
        "query_result": query_result,
        "final_answer": final_answer,
        "retry_count": 0,
        "max_retries": 0,
        "error_type": None if validation_result.get("valid") else "baseline_error",
        "execution_stats": execution_stats,
    }
