"""SQL generation node: produce robust read-only SQL from schema and question."""

import logging
import re
from typing import Any, Dict, List

from agent.state import AgentState, get_field_mapping
from services.conversation_service import build_history_context_text, get_recent_chat_history
from services.knowledge_base import get_knowledge_base
from services.llm_service import get_llm_service

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def sql_generate_node(state: AgentState) -> Dict[str, Any]:
    """Generate SQL from resolved question, schema context, and optional KB examples."""
    question = state["question"]
    resolved_question = state.get("resolved_question") or question
    intent = dict(state.get("intent", {}))
    schemas = state.get("relevant_schemas", [])
    chat_history = get_recent_chat_history(state.get("chat_history", []), max_turns=5)
    retry_count = state.get("retry_count", 0)
    validation_result = state.get("validation_result", {})

    logger.info("[SQL Generate] Generating SQL for question: %s", resolved_question)

    try:
        schema_text = build_schema_description(schemas)

        time_range = intent.get("time_range")
        if time_range:
            intent["time_expression"] = get_field_mapping(time_range)

        examples_text = ""
        try:
            kb = get_knowledge_base()
            search_query = build_example_search_query(resolved_question, intent, chat_history)
            example_results = kb.search_sql_examples(search_query, n_results=3)
            examples_text = format_sql_examples(example_results)
        except Exception as exc:
            logger.warning("[SQL Generate] Failed to retrieve SQL examples: %s", exc)

        retry_hint = build_retry_hint(retry_count, validation_result.get("error", ""))
        question_with_history = build_question_with_history(resolved_question, chat_history)

        sql = ""
        try:
            db_uri = str(state.get("db_uri", ""))
            dialect = "sqlite" if "sqlite" in db_uri.lower() else "postgresql"

            llm = get_llm_service()
            llm_response = llm.generate_sql(
                schemas=schema_text,
                question=question_with_history,
                intent=intent,
                examples=examples_text,
                retry_hint=retry_hint,
                dialect=dialect,
            )
            sql = extract_sql_from_llm_response(llm_response)
            sql = align_sql_with_question(sql, resolved_question)
            logger.info("[SQL Generate] SQL generated by LLM")
        except Exception as exc:
            logger.warning("[SQL Generate] LLM unavailable, fallback to rules: %s", exc)
            sql = generate_sql_with_rules(resolved_question, intent, schemas)

        normalized_sql = (sql or "").strip().lower()
        if not normalized_sql or not (normalized_sql.startswith("select") or normalized_sql.startswith("with")):
            logger.warning("[SQL Generate] Invalid SQL from generator, fallback to rules")
            sql = generate_sql_with_rules(resolved_question, intent, schemas)

        sql = (sql or "").strip()
        logger.info("[SQL Generate] Generated SQL: %s", sql)
        return {
            "generated_sql": sql,
            "messages": state["messages"],
        }

    except Exception as exc:
        logger.error("[SQL Generate] Error: %s", exc)
        return {
            "generated_sql": "",
            "messages": state["messages"],
        }


def build_question_with_history(question: str, chat_history: list) -> str:
    """Append recent chat context for follow-up questions."""
    history_text = build_history_context_text(chat_history, max_messages=4)
    if not history_text:
        return question
    return f"Recent conversation context:\n{history_text}\n\nCurrent question: {question}"


def build_example_search_query(question: str, intent: dict, chat_history: list) -> str:
    """Build search query for retrieving similar SQL examples."""
    parts = [question]
    parts.extend(intent.get("entities", []))

    query_type = intent.get("query_type")
    if query_type:
        parts.append(str(query_type))

    time_range = intent.get("time_range")
    if time_range:
        parts.append(str(time_range))

    if chat_history:
        last_user_msgs = [msg.get("content", "") for msg in chat_history[-4:] if msg.get("role") == "user"]
        parts.extend([str(msg) for msg in last_user_msgs if msg])

    return " ".join(str(part) for part in parts if part)


def build_retry_hint(retry_count: int, error_message: str) -> str:
    """Build a retry hint to reduce repeated SQL errors."""
    if retry_count <= 0 or not error_message:
        return ""
    return (
        "\n\nPrevious SQL failed validation with error: "
        f"{error_message}\nPlease avoid repeating the same issue."
    )


def build_schema_description(schemas: list) -> str:
    """Build schema description for LLM SQL generation."""
    if not schemas:
        return "No schemas available"

    description = "Database Schema:\n\n"
    for schema in schemas:
        description += f"Table: {schema['table_name']}\n"
        description += f"DDL: {schema['ddl']}\n"
        description += f"Columns: {len(schema['columns'])}\n"
        description += f"Rows: {schema['row_count']}\n"
        primary_keys = schema.get("primary_keys", [])
        foreign_keys = schema.get("foreign_keys", [])
        if primary_keys:
            description += f"Primary keys: {', '.join(str(pk) for pk in primary_keys)}\n"
        if foreign_keys:
            description += "Foreign keys:\n"
            for fk in foreign_keys:
                cols = ", ".join(str(col) for col in fk.get("columns", []))
                ref_table = fk.get("ref_table", "")
                ref_cols = ", ".join(str(col) for col in fk.get("ref_columns", []))
                description += f"  - ({cols}) -> {ref_table}({ref_cols})\n"

        cols = schema.get("columns", [])
        if cols:
            description += "Column details:\n"
            for col in cols:
                col_name = col.get("name", "")
                col_type = col.get("type", "")
                description += f"  - {col_name} ({col_type})\n"
        description += "\n"
    return description


def format_sql_examples(example_results: List[Dict[str, Any]]) -> str:
    """Format retrieved SQL examples for prompt context."""
    if not example_results:
        return "None"

    formatted = []
    for index, item in enumerate(example_results, start=1):
        formatted.append(f"Example {index}:\n{item.get('document', '')}")
    return "\n\n".join(formatted)


def generate_sql_with_rules(question: str, intent: dict, schemas: list) -> str:
    """Rule-based fallback SQL generation when LLM is unavailable."""
    query_type = intent.get("query_type", "unknown")
    entities = intent.get("entities", [])
    limit = intent.get("limit", 100)
    time_expression = intent.get("time_expression")

    if query_type == "count":
        if "orders" in entities:
            if time_expression:
                return f"SELECT COUNT(*) as count FROM orders WHERE {time_expression}"
            return "SELECT COUNT(*) as count FROM orders"
        if "users" in entities:
            return "SELECT COUNT(*) as count FROM users"
        if "products" in entities:
            return "SELECT COUNT(*) as count FROM products"

    elif query_type == "ranking":
        if "sales" in entities:
            return f"""
SELECT p.category as dimension, SUM(oi.quantity * oi.unit_price) as total_sales
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN users u ON o.user_id = u.user_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_sales DESC
LIMIT {limit}
            """.strip()

        if "reviews" in entities or "rating" in entities:
            return f"""
SELECT p.product_name, AVG(r.rating) as avg_rating
FROM reviews r
JOIN products p ON r.product_id = p.product_id
GROUP BY p.product_id, p.product_name
HAVING COUNT(*) >= 5
ORDER BY avg_rating DESC
LIMIT {limit}
            """.strip()

    elif query_type == "distribution":
        if "users" in entities:
            return f"""
SELECT city, COUNT(*) as user_count
FROM users
GROUP BY city
ORDER BY user_count DESC
LIMIT {limit}
            """.strip()

        if "products" in entities:
            return f"""
SELECT category, COUNT(*) as product_count
FROM products
GROUP BY category
ORDER BY product_count DESC
LIMIT {limit}
            """.strip()

    elif query_type == "trend":
        return """
SELECT DATE(order_date) as order_day, AVG(total_amount) as avg_amount
FROM orders
GROUP BY DATE(order_date)
ORDER BY order_day
LIMIT 30
        """.strip()

    elif query_type == "repurchase_rate" or "repurchase" in question.lower():
        where_clause = f"WHERE {time_expression}" if time_expression else ""
        return f"""
WITH user_orders AS (
    SELECT user_id, COUNT(*) AS order_count
    FROM orders
    {where_clause}
    GROUP BY user_id
)
SELECT ROUND(
    COUNT(CASE WHEN order_count > 1 THEN 1 END) * 1.0 / NULLIF(COUNT(*), 0),
    4
) AS repurchase_rate
FROM user_orders
        """.strip()

    return ""


def extract_sql_from_llm_response(response: str) -> str:
    """Extract SQL from LLM response text."""
    if not response:
        return ""

    fenced_blocks = re.findall(r"```(?:sql)?\s*(.*?)\s*```", response, re.DOTALL | re.IGNORECASE)
    if fenced_blocks:
        candidates = [block.strip() for block in fenced_blocks if block and block.strip()]
        if candidates:
            best = max(candidates, key=len)
            return sanitize_sql_structure(best)

    sql_match = re.search(r"((?:WITH|SELECT)\b.*?)(?:;\s*)?$", response, re.DOTALL | re.IGNORECASE)
    if sql_match:
        return sanitize_sql_structure(sql_match.group(1))

    return sanitize_sql_structure(response)


def sanitize_sql_structure(sql_text: str) -> str:
    """Lightweight SQL text cleanup for common LLM output artifacts."""
    sql = str(sql_text or "").strip()
    if not sql:
        return ""

    sql = sql.replace("\r\n", "\n").strip()
    sql = re.sub(r"^```(?:sql)?\s*", "", sql, flags=re.IGNORECASE).strip()
    sql = re.sub(r"\s*```$", "", sql).strip()

    start_match = re.search(r"\b(?:WITH|SELECT)\b", sql, re.IGNORECASE)
    if start_match:
        sql = sql[start_match.start() :].strip()

    sql = re.split(r"\n\s*(?:Explanation|Reasoning|Answer)\s*:", sql, maxsplit=1, flags=re.IGNORECASE)[0].strip()
    sql = _repair_missing_with_cte(sql)
    sql = _repair_misplaced_distinct(sql)

    sql = sql.rstrip()
    if sql.count(";") > 1:
        sql = sql.split(";")[0].strip()
    if sql.endswith(";"):
        sql = sql[:-1].rstrip()

    return sql


def _repair_missing_with_cte(sql: str) -> str:
    """Fix malformed pattern: `SELECT ... ) SELECT ... JOIN cte ...` without `WITH`."""
    if not sql or re.match(r"^\s*WITH\b", sql, flags=re.IGNORECASE):
        return sql

    pattern = re.compile(r"^\s*(SELECT[\s\S]+?)\)\s*(SELECT[\s\S]+)\s*$", re.IGNORECASE)
    match = pattern.match(sql)
    if not match:
        return sql

    first_select = match.group(1).strip()
    second_select = match.group(2).strip()
    cte_name = _infer_cte_name_from_second_select(second_select)
    if not cte_name:
        return sql

    return f"WITH {cte_name} AS (\n{first_select}\n)\n{second_select}"


def _infer_cte_name_from_second_select(second_select: str) -> str:
    """Infer CTE name from JOIN/CROSS JOIN alias usage in downstream SELECT."""
    for regex in [
        r"\bJOIN\s+([A-Za-z_][A-Za-z0-9_]*)\s+[A-Za-z_][A-Za-z0-9_]*\b",
        r"\bCROSS\s+JOIN\s+([A-Za-z_][A-Za-z0-9_]*)\s+[A-Za-z_][A-Za-z0-9_]*\b",
    ]:
        join_match = re.search(regex, second_select, re.IGNORECASE)
        if join_match:
            token = join_match.group(1)
            if token.lower() not in {"select", "from", "where", "group", "order", "limit"}:
                return token
    return ""


def _repair_misplaced_distinct(sql: str) -> str:
    """Repair malformed projection like `SELECT a, DISTINCT b FROM ...`."""
    pattern = re.compile(r"^\s*SELECT\s+(.+?)\s+FROM\s+([\s\S]+)$", re.IGNORECASE)
    match = pattern.match(sql.strip())
    if not match:
        return sql

    select_expr = match.group(1).strip()
    if re.match(r"(?i)^distinct\b", select_expr):
        return sql
    if "distinct" not in select_expr.lower():
        return sql

    parts = split_select_items(select_expr)
    fixed_parts: List[str] = []
    seen_distinct = False
    for part in parts:
        stripped = part.strip()
        if re.match(r"(?i)^distinct\b", stripped):
            seen_distinct = True
            stripped = re.sub(r"(?i)^distinct\s+", "", stripped).strip()
        if stripped:
            fixed_parts.append(stripped)

    if not seen_distinct or not fixed_parts:
        return sql
    return f"SELECT DISTINCT {', '.join(fixed_parts)} FROM {match.group(2).strip()}"


def align_sql_with_question(sql_text: str, question: str) -> str:
    """Apply small deterministic rewrites so SQL output shape better matches question intent."""
    sql = sanitize_sql_structure(sql_text)
    if not sql:
        return sql

    q = (question or "").strip().lower()
    sql = _normalize_country_demonyms(sql)
    sql = _trim_year_count_projection(sql, q)
    sql = _drop_unasked_id_projection(sql, q)
    sql = _prune_extra_projection_columns(sql, q)
    sql = _prefer_inner_join_for_count_per_entity(sql, q)
    sql = _align_name_id_order(sql, q)
    return sql


def _normalize_country_demonyms(sql: str) -> str:
    """Normalize common demonyms to country names to reduce zero-result mistakes."""
    replacements = {
        "'french'": "'France'",
        "'german'": "'Germany'",
        "'american'": "'USA'",
        "'british'": "'UK'",
        "'chinese'": "'China'",
    }
    fixed = sql
    for src, dst in replacements.items():
        fixed = re.sub(src, dst, fixed, flags=re.IGNORECASE)
    return fixed


def _trim_year_count_projection(sql: str, question_lower: str) -> str:
    """For 'which year ... most ...' questions, avoid returning helper count column."""
    if not (("which year" in question_lower or "what is the year" in question_lower) and ("most" in question_lower or "highest" in question_lower)):
        return sql

    pattern = re.compile(
        r"^\s*SELECT\s+([A-Za-z_][\w\.]*)\s*,\s*COUNT\s*\(\s*\*\s*\)\s+AS\s+[A-Za-z_]\w*\s+(FROM[\s\S]+)$",
        re.IGNORECASE,
    )
    match = pattern.match(sql.strip())
    if not match:
        return sql

    year_col = match.group(1)
    suffix = match.group(2)
    return f"SELECT {year_col} {suffix}"


def _reorder_group_aggregate_projection(sql: str, question_lower: str) -> str:
    """Reorder projection to put aggregates before grouped dimension when question asks that order."""
    if "for each" not in question_lower and "each " not in question_lower:
        return sql
    aggregate_terms = ["average", "avg", "maximum", "minimum", "count", "sum", "total", "max", "min"]
    if not any(term in question_lower for term in aggregate_terms):
        return sql

    pattern = re.compile(r"^\s*SELECT\s+(.+?)\s+FROM\s+([\s\S]+)$", re.IGNORECASE)
    match = pattern.match(sql.strip())
    if not match:
        return sql

    select_expr = match.group(1).strip()
    from_expr = match.group(2).strip()
    parts = split_select_items(select_expr)
    if len(parts) < 2:
        return sql

    agg_parts = [p for p in parts if re.search(r"\b(count|avg|min|max|sum)\s*\(", p, re.IGNORECASE)]
    dim_parts = [p for p in parts if p not in agg_parts]
    if not agg_parts or not dim_parts:
        return sql
    if parts == agg_parts + dim_parts:
        return sql

    return f"SELECT {', '.join(agg_parts + dim_parts)} FROM {from_expr}"


def _drop_unasked_id_projection(sql: str, question_lower: str) -> str:
    """Drop leading id column when question asks names/counts but not ids."""
    if re.search(r"\bids?\b", question_lower) or "identifier" in question_lower or "编号" in question_lower:
        return sql
    if not ("how many" in question_lower or "number of" in question_lower):
        return sql

    pattern = re.compile(r"^\s*SELECT\s+(.+?)\s+FROM\s+([\s\S]+)$", re.IGNORECASE)
    match = pattern.match(sql.strip())
    if not match:
        return sql

    select_expr = match.group(1).strip()
    from_expr = match.group(2).strip()
    parts = split_select_items(select_expr)
    if len(parts) < 2:
        return sql

    first = parts[0].lower()
    has_count = any(re.search(r"\bcount\s*\(", p, re.IGNORECASE) for p in parts)
    if has_count and (".id" in first or first.endswith("id") or " id" in first):
        return f"SELECT {', '.join(parts[1:])} FROM {from_expr}"
    return sql


def _prune_extra_projection_columns(sql: str, question_lower: str) -> str:
    """Trim extra SELECT columns for count-per-entity questions."""
    if not ("how many" in question_lower or "number of" in question_lower):
        return sql
    if not ("for each" in question_lower or "each " in question_lower or " per " in question_lower):
        return sql

    pattern = re.compile(r"^\s*SELECT\s+(.+?)\s+FROM\s+([\s\S]+)$", re.IGNORECASE)
    match = pattern.match(sql.strip())
    if not match:
        return sql

    select_expr = match.group(1).strip()
    from_expr = match.group(2).strip()
    parts = split_select_items(select_expr)
    if len(parts) <= 2:
        return sql

    agg_parts = [part for part in parts if re.search(r"\b(count|avg|min|max|sum)\s*\(", part, re.IGNORECASE)]
    dim_parts = [part for part in parts if part not in agg_parts]
    if not agg_parts or not dim_parts:
        return sql

    prefer_id = bool(re.search(r"\bids?\b", question_lower) or "identifier" in question_lower)
    if prefer_id:
        dim = next((part for part in dim_parts if _contains_id_token(part)), dim_parts[0])
    else:
        dim = next(
            (part for part in dim_parts if not _contains_id_token(part)),
            dim_parts[0],
        )

    return f"SELECT {dim}, {agg_parts[0]} FROM {from_expr}"


def _align_name_id_order(sql: str, question_lower: str) -> str:
    """Align projection order for common 'name/id' phrasing in question."""
    has_name = bool(re.search(r"\bname\b|\bnames\b|full name", question_lower))
    has_id = bool(re.search(r"\bids?\b|\bidentifier\b", question_lower))
    if not (has_name and has_id):
        return sql

    pattern = re.compile(r"^\s*SELECT\s+(.+?)\s+FROM\s+([\s\S]+)$", re.IGNORECASE)
    match = pattern.match(sql.strip())
    if not match:
        return sql

    parts = split_select_items(match.group(1).strip())
    if len(parts) < 2:
        return sql

    name_idx = next((i for i, part in enumerate(parts) if _contains_name_token(part)), None)
    id_idx = next((i for i, part in enumerate(parts) if _contains_id_token(part)), None)
    if name_idx is None or id_idx is None:
        return sql

    wants_name_first = bool(re.search(r"(name|names|full name).{0,40}(id|ids|identifier)", question_lower))
    wants_id_first = bool(re.search(r"(id|ids|identifier).{0,40}(name|names|full name)", question_lower))
    if not (wants_name_first or wants_id_first):
        return sql

    if wants_name_first and name_idx > id_idx:
        parts[name_idx], parts[id_idx] = parts[id_idx], parts[name_idx]
    elif wants_id_first and id_idx > name_idx:
        parts[name_idx], parts[id_idx] = parts[id_idx], parts[name_idx]
    else:
        return sql

    from_expr = match.group(2).strip()
    return f"SELECT {', '.join(parts)} FROM {from_expr}"


def _prefer_inner_join_for_count_per_entity(sql: str, question_lower: str) -> str:
    """Prefer INNER JOIN in count-per-entity questions unless inclusiveness is explicit."""
    if not ("how many" in question_lower or "number of" in question_lower):
        return sql
    if not ("for each" in question_lower or "each " in question_lower or " per " in question_lower):
        return sql
    if any(token in question_lower for token in ["including", "include", "even if", "no "]):
        return sql
    return re.sub(r"\bLEFT\s+JOIN\b", "JOIN", sql, flags=re.IGNORECASE)


def _contains_id_token(expr: str) -> bool:
    """Check whether a projection expression looks like an ID field."""
    text = str(expr or "").strip().lower()
    if not text:
        return False
    if ".id" in text or "_id" in text:
        return True
    return bool(re.search(r"\b\w*id\b", text))


def _contains_name_token(expr: str) -> bool:
    """Check whether a projection expression looks like a name field."""
    text = str(expr or "").strip().lower()
    if not text:
        return False
    if ".name" in text or "_name" in text:
        return True
    return bool(re.search(r"\b\w*name\b", text))


def split_select_items(select_expr: str) -> List[str]:
    """Split SELECT item list by top-level commas."""
    items: List[str] = []
    current: List[str] = []
    depth = 0

    for ch in select_expr:
        if ch == "(":
            depth += 1
        elif ch == ")" and depth > 0:
            depth -= 1
        elif ch == "," and depth == 0:
            item = "".join(current).strip()
            if item:
                items.append(item)
            current = []
            continue
        current.append(ch)

    tail = "".join(current).strip()
    if tail:
        items.append(tail)
    return items
