"""
SQL 生成节点 - 根据意图和 Schema 生成 SQL
"""
import logging
import re
from typing import Any, Dict, List

from agent.state import AgentState, get_field_mapping
from services.conversation_service import build_history_context_text, get_recent_chat_history
from services.knowledge_base import get_knowledge_base
from services.llm_service import get_llm_service


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)



def sql_generate_node(state: AgentState) -> Dict[str, Any]:
    """
    SQL 生成节点 - 基于 Schema、意图和知识库示例生成 SQL

    优先使用 LLM 生成；若 LLM 不可用，则降级为规则生成。
    """
    question = state["question"]
    resolved_question = state.get("resolved_question") or question
    intent = dict(state.get("intent", {}))
    schemas = state.get("relevant_schemas", [])
    chat_history = get_recent_chat_history(state.get("chat_history", []), max_turns=5)
    retry_count = state.get("retry_count", 0)
    validation_result = state.get("validation_result", {})

    logger.info(f"[SQL Generate] Generating SQL for question: {resolved_question}")

    try:
        schema_text = build_schema_description(schemas)
        llm_unavailable = False


        time_range = intent.get("time_range")
        if time_range:
            intent["time_expression"] = get_field_mapping(time_range)

        examples_text = ""
        try:
            kb = get_knowledge_base()
            search_query = build_example_search_query(resolved_question, intent, chat_history)
            example_results = kb.search_sql_examples(search_query, n_results=3)
            examples_text = format_sql_examples(example_results)
        except Exception as e:
            logger.warning(f"[SQL Generate] Failed to retrieve SQL examples: {e}")

        retry_hint = build_retry_hint(retry_count, validation_result.get("error", ""))
        question_with_history = build_question_with_history(resolved_question, chat_history)

        sql = ""
        try:
            # Detect database dialect from db_uri
            db_uri = str(state.get("db_uri", ""))
            dialect = "sqlite" if "sqlite" in db_uri.lower() else "postgresql"

            llm = get_llm_service()
            llm_response = llm.generate_sql(
                schemas=schema_text,
                question=question_with_history,
                intent=intent,
                examples=examples_text,
                retry_hint=retry_hint,
                dialect=dialect,
            )
            sql = extract_sql_from_llm_response(llm_response)
            logger.info("[SQL Generate] SQL generated by LLM")
        except Exception as e:
            logger.warning(f"[SQL Generate] LLM unavailable, fallback to rules: {e}")
            llm_unavailable = True
            sql = generate_sql_with_rules(resolved_question, intent, schemas)


        normalized_sql = (sql or "").strip().lower()
        if not normalized_sql or not (normalized_sql.startswith("select") or normalized_sql.startswith("with")):
            logger.warning("[SQL Generate] Invalid SQL from generator, fallback to rules")
            sql = generate_sql_with_rules(resolved_question, intent, schemas)


        sql = sql.strip()
        logger.info(f"[SQL Generate] Generated SQL: {sql}")
        return {
            "generated_sql": sql,
            "messages": state["messages"],
        }

    except Exception as e:
        logger.error(f"[SQL Generate] Error: {e}")
        return {
            "generated_sql": "",
            "messages": state["messages"],
        }



def build_question_with_history(question: str, chat_history: list) -> str:
    """将最近对话上下文拼接进问题中，增强多轮生成效果。"""
    history_text = build_history_context_text(chat_history, max_messages=4)
    if not history_text:
        return question

    return f"最近对话上下文:\n{history_text}\n\n当前问题: {question}"



def build_example_search_query(question: str, intent: dict, chat_history: list) -> str:
    """构建相似 SQL 示例检索 query。"""
    parts = [question]
    parts.extend(intent.get("entities", []))

    query_type = intent.get("query_type")
    if query_type:
        parts.append(str(query_type))

    time_range = intent.get("time_range")
    if time_range:
        parts.append(str(time_range))

    if chat_history:
        last_user_msgs = [msg.get("content", "") for msg in chat_history[-4:] if msg.get("role") == "user"]
        parts.extend([str(msg) for msg in last_user_msgs if msg])

    return " ".join(str(part) for part in parts if part)



def build_retry_hint(retry_count: int, error_message: str) -> str:
    """构建重试提示。"""
    if retry_count <= 0 or not error_message:
        return ""
    return f"\n\n上一次生成的 SQL 校验失败，错误信息：{error_message}\n请避免再次出现相同问题。"



def build_schema_description(schemas: list) -> str:
    """构建 Schema 描述用于 LLM。"""
    if not schemas:
        return "No schemas available"

    description = "Database Schema:\n\n"
    for schema in schemas:
        description += f"Table: {schema['table_name']}\n"
        description += f"DDL: {schema['ddl']}\n"
        description += f"Columns: {len(schema['columns'])}\n"
        description += f"Rows: {schema['row_count']}\n\n"
    return description



def format_sql_examples(example_results: List[Dict[str, Any]]) -> str:
    """格式化相似 SQL 示例。"""
    if not example_results:
        return "无"

    formatted = []
    for index, item in enumerate(example_results, start=1):
        formatted.append(f"示例 {index}:\n{item.get('document', '')}")
    return "\n\n".join(formatted)



def generate_sql_with_rules(question: str, intent: dict, schemas: list) -> str:
    """使用规则生成 SQL（作为降级方案）。"""
    query_type = intent.get("query_type", "unknown")
    entities = intent.get("entities", [])
    limit = intent.get("limit", 100)
    time_expression = intent.get("time_expression")

    if query_type == "count":
        if "订单" in entities or "orders" in entities:
            if time_expression:
                return f"SELECT COUNT(*) as count FROM orders WHERE {time_expression}"
            return "SELECT COUNT(*) as count FROM orders"

        if "用户" in entities or "users" in entities:
            return "SELECT COUNT(*) as count FROM users"

        if "产品" in entities or "products" in entities:
            return "SELECT COUNT(*) as count FROM products"

    elif query_type == "ranking":
        if "销售额" in entities or "sales" in entities:
            group_dimension = "p.category"
            if "城市" in entities:
                group_dimension = "u.city"
            return f"""
SELECT {group_dimension} as dimension, SUM(oi.quantity * oi.unit_price) as total_sales
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN users u ON o.user_id = u.user_id
JOIN products p ON oi.product_id = p.product_id
GROUP BY {group_dimension}
ORDER BY total_sales DESC
LIMIT {limit}
            """.strip()

        if "评分" in entities or "rating" in entities:
            return f"""
SELECT p.product_name, AVG(r.rating) as avg_rating
FROM reviews r
JOIN products p ON r.product_id = p.product_id
GROUP BY p.product_id, p.product_name
HAVING COUNT(*) >= 5
ORDER BY avg_rating DESC
LIMIT {limit}
            """.strip()

    elif query_type == "distribution":
        if "用户" in entities or "users" in entities:
            group_dimension = "city"
            return f"""
SELECT {group_dimension}, COUNT(*) as user_count
FROM users
GROUP BY {group_dimension}
ORDER BY user_count DESC
LIMIT {limit}
            """.strip()

        if "产品" in entities or "products" in entities:
            return f"""
SELECT category, COUNT(*) as product_count
FROM products
GROUP BY category
ORDER BY product_count DESC
LIMIT {limit}
            """.strip()

    elif query_type == "trend":
        return """
SELECT DATE(order_date) as order_day, AVG(total_amount) as avg_amount
FROM orders
GROUP BY DATE(order_date)
ORDER BY order_day
LIMIT 30
        """.strip()

    elif query_type == "repurchase_rate" or "复购率" in question or "复购" in question:
        where_clause = f"WHERE {time_expression}" if time_expression else ""
        return f"""
WITH user_orders AS (
    SELECT user_id, COUNT(*) AS order_count
    FROM orders
    {where_clause}
    GROUP BY user_id
)
SELECT ROUND(
    COUNT(*) FILTER (WHERE order_count > 1)::DECIMAL / NULLIF(COUNT(*), 0),
    4
) AS repurchase_rate
FROM user_orders
        """.strip()

    if "上月" in question and time_expression:
        return f"SELECT COUNT(*) as count FROM orders WHERE {time_expression}"

    return ""





def extract_sql_from_llm_response(response: str) -> str:
    """从 LLM 响应中提取 SQL。"""
    if not response:
        return ""

    sql_match = re.search(r"```sql\s*(.*?)\s*```", response, re.DOTALL | re.IGNORECASE)
    if sql_match:
        return sql_match.group(1).strip()

    sql_match = re.search(r"(SELECT\b.*?)(?:;\s*)?$", response, re.DOTALL | re.IGNORECASE)
    if sql_match:
        return sql_match.group(1).strip()

    return response.strip()
