"""
SQL 生成节点 - 根据意图和 Schema 生成 SQL
"""
import logging
import re
from typing import Any, Dict, List

from agent.state import AgentState, get_field_mapping
from config import DEEPSEEK_API_KEY
from services.knowledge_base import get_knowledge_base
from services.llm_service import get_llm_service


# 配置日志
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def sql_generate_node(state: AgentState) -> Dict[str, Any]:
    """
    SQL 生成节点 - 基于 Schema、意图和知识库示例生成 SQL

    优先使用 LLM 生成；若 LLM 不可用，则降级为规则生成。
    """
    question = state["question"]
    intent = dict(state.get("intent", {}))
    schemas = state.get("relevant_schemas", [])
    chat_history = state.get("chat_history", [])
    retry_count = state.get("retry_count", 0)
    validation_result = state.get("validation_result", {})

    logger.info(f"[SQL Generate] Generating SQL for question: {question}")

    try:
        schema_text = build_schema_description(schemas)

        time_range = intent.get("time_range")
        if time_range:
            intent["time_expression"] = get_field_mapping(time_range)

        examples_text = ""
        try:
            kb = get_knowledge_base()
            search_query = build_example_search_query(question, intent, chat_history)
            example_results = kb.search_sql_examples(search_query, n_results=3)
            examples_text = format_sql_examples(example_results)
        except Exception as e:
            logger.warning(f"[SQL Generate] Failed to retrieve SQL examples: {e}")

        retry_hint = build_retry_hint(retry_count, validation_result.get("error", ""))
        question_with_history = build_question_with_history(question, chat_history)

        sql = ""
        try:
            if not DEEPSEEK_API_KEY:
                raise ValueError("DEEPSEEK_API_KEY 未设置")

            llm = get_llm_service()
            llm_response = llm.generate_sql(
                schemas=schema_text,
                question=question_with_history,
                intent=intent,
                examples=examples_text,
                retry_hint=retry_hint,
            )
            sql = extract_sql_from_llm_response(llm_response)
            logger.info("[SQL Generate] SQL generated by LLM")
        except Exception as e:
            logger.warning(f"[SQL Generate] LLM unavailable, fallback to rules: {e}")
            sql = generate_sql_with_rules(question, intent, schemas)


        if not sql or not sql.strip().lower().startswith("select"):
            logger.warning("[SQL Generate] Invalid SQL from generator, fallback to rules")
            sql = generate_sql_with_rules(question, intent, schemas)

        sql = sql.strip()
        logger.info(f"[SQL Generate] Generated SQL: {sql}")
        return {
            "generated_sql": sql,
            "messages": state["messages"],
        }

    except Exception as e:
        logger.error(f"[SQL Generate] Error: {e}")
        return {
            "generated_sql": "",
            "messages": state["messages"],
        }


def build_question_with_history(question: str, chat_history: list) -> str:
    """将最近对话上下文拼接进问题中，增强多轮生成效果。"""
    if not chat_history:
        return question

    history_lines = []
    for msg in chat_history[-4:]:
        role = msg.get("role", "user")
        content = str(msg.get("content", "")).strip()
        if content:
            history_lines.append(f"{role}: {content}")

    if not history_lines:
        return question

    return f"最近对话上下文:\n" + "\n".join(history_lines) + f"\n\n当前问题: {question}"


def build_example_search_query(question: str, intent: dict, chat_history: list) -> str:
    """构建相似 SQL 示例检索 query。"""
    parts = [question]
    parts.extend(intent.get("entities", []))

    query_type = intent.get("query_type")
    if query_type:
        parts.append(str(query_type))

    time_range = intent.get("time_range")
    if time_range:
        parts.append(str(time_range))

    if chat_history:
        last_user_msgs = [msg.get("content", "") for msg in chat_history[-2:] if msg.get("role") == "user"]
        parts.extend([str(msg) for msg in last_user_msgs if msg])

    return " ".join(str(part) for part in parts if part)


def build_retry_hint(retry_count: int, error_message: str) -> str:
    """构建重试提示。"""
    if retry_count <= 0 or not error_message:
        return ""
    return f"\n\n上一次生成的 SQL 校验失败，错误信息：{error_message}\n请避免再次出现相同问题。"


def build_schema_description(schemas: list) -> str:
    """构建 Schema 描述用于 LLM。"""
    if not schemas:
        return "No schemas available"

    description = "Database Schema:\n\n"
    for schema in schemas:
        description += f"Table: {schema['table_name']}\n"
        description += f"DDL: {schema['ddl']}\n"
        description += f"Columns: {len(schema['columns'])}\n"
        description += f"Rows: {schema['row_count']}\n\n"
    return description


def format_sql_examples(example_results: List[Dict[str, Any]]) -> str:
    """格式化相似 SQL 示例。"""
    if not example_results:
        return "无"

    formatted = []
    for index, item in enumerate(example_results, start=1):
        formatted.append(f"示例 {index}:\n{item.get('document', '')}")
    return "\n\n".join(formatted)


def generate_sql_with_rules(question: str, intent: dict, schemas: list) -> str:
    """使用规则生成 SQL（作为降级方案）。"""
    query_type = intent.get("query_type", "unknown")
    entities = intent.get("entities", [])
    limit = intent.get("limit", 100)
    time_expression = intent.get("time_expression")

    if query_type == "count":
        if "订单" in entities or "orders" in entities:
            if time_expression:
                return f"SELECT COUNT(*) as count FROM orders WHERE {time_expression}"
            return "SELECT COUNT(*) as count FROM orders"

        if "用户" in entities or "users" in entities:
            return "SELECT COUNT(*) as count FROM users"

        if "产品" in entities or "products" in entities:
            return "SELECT COUNT(*) as count FROM products"

    elif query_type == "ranking":
        if "销售额" in entities or "sales" in entities:
            return f"""
SELECT p.category, SUM(oi.quantity * oi.unit_price) as total_sales
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_sales DESC
LIMIT {limit}
            """.strip()

        if "评分" in entities or "rating" in entities:
            return f"""
SELECT p.product_name, AVG(r.rating) as avg_rating
FROM reviews r
JOIN products p ON r.product_id = p.product_id
GROUP BY p.product_id, p.product_name
HAVING COUNT(*) >= 5
ORDER BY avg_rating DESC
LIMIT {limit}
            """.strip()

    elif query_type == "distribution":
        if "用户" in entities or "users" in entities:
            return f"""
SELECT city, COUNT(*) as user_count
FROM users
GROUP BY city
ORDER BY user_count DESC
LIMIT {limit}
            """.strip()

        if "产品" in entities or "products" in entities:
            return f"""
SELECT category, COUNT(*) as product_count
FROM products
GROUP BY category
ORDER BY product_count DESC
LIMIT {limit}
            """.strip()

    return "SELECT * FROM users LIMIT 10"


def extract_sql_from_llm_response(response: str) -> str:
    """从 LLM 响应中提取 SQL。"""
    if not response:
        return ""

    sql_match = re.search(r"```sql\s*(.*?)\s*```", response, re.DOTALL | re.IGNORECASE)
    if sql_match:
        return sql_match.group(1).strip()

    sql_match = re.search(r"(SELECT\b.*?)(?:;\s*)?$", response, re.DOTALL | re.IGNORECASE)
    if sql_match:
        return sql_match.group(1).strip()

    return response.strip()
